const APP_TITLE = "Todo App";
const ADD_BUTTON_TEXT = "ADD";
const UPDATE_BUTTON_TEXT = "UPDATE";
const CANCEL_BUTTON_TEXT = "CANCEL";
const EDIT_BUTTON_TEXT = "EDIT";
const DELETE_BUTTON_TEXT = "DELETE";

export {
  APP_TITLE,
  ADD_BUTTON_TEXT,
  UPDATE_BUTTON_TEXT,
  CANCEL_BUTTON_TEXT,
  EDIT_BUTTON_TEXT,
  DELETE_BUTTON_TEXT,
};
